# Generated by Django 2.1.11 on 2020-02-24 12:42

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='文章标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('type', models.CharField(choices=[('a', '文章'), ('p', '页面')], default='a', max_length=1, verbose_name='文章类型')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='越大越前', verbose_name='排序')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '2-文章',
                'verbose_name_plural': '2-文章',
                'ordering': ['-order', '-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='分类')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='越大越前', verbose_name='排序')),
                ('slug', models.SlugField(default='')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '1-文章分类',
                'verbose_name_plural': '1-文章分类',
                'ordering': ['-order', 'add_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('content', models.TextField(max_length=250, verbose_name='评论内容')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否显示')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='评论文章')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '3-文章评论',
                'verbose_name_plural': '3-文章评论',
            },
        ),
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('content', models.TextField(max_length=250, verbose_name='留言内容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言者')),
            ],
            options={
                'verbose_name': '7-留言板',
                'verbose_name_plural': '7-留言板',
                'ordering': ['author', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='链接名称')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='越大越前', verbose_name='排序')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '8-友情链接',
                'verbose_name_plural': '8-友情链接',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('title', models.CharField(help_text='用于当作照片名称', max_length=50, verbose_name='图片标题')),
                ('desc', models.TextField(blank=True, help_text='用于图片标签的title属性', max_length=200, null=True, verbose_name='图片描述')),
                ('image', models.ImageField(help_text='默认保存在/media/photo/', upload_to=blog.models.photo_path, verbose_name='图片')),
            ],
            options={
                'verbose_name': '6-相册图片',
                'verbose_name_plural': '6-相册图片',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('desc', models.TextField(blank=True, default='', verbose_name='站点描述')),
                ('keyword', models.TextField(blank=True, default='', verbose_name='站点关键字')),
                ('article_desc_len', models.IntegerField(default=250, verbose_name='文章摘要长度')),
                ('sidebar_article_count', models.IntegerField(default=10, verbose_name='侧边栏文章条数')),
                ('enable_photo', models.BooleanField(default=True, verbose_name='是否启用相册')),
                ('user_verify_email', models.BooleanField(default=False, verbose_name='用户注册是否验证邮箱')),
                ('enable_multi_user', models.BooleanField(default=False, help_text='是否启用多用户博客系统, 注册用户只具有对自己文章的增删改查权限', verbose_name='是否启用多用户博客系统')),
                ('github_user', models.CharField(default='enjoy-binbin', help_text='https://github.com/enjoy-binbin', max_length=50, verbose_name='github账号')),
                ('github_repository', models.CharField(default='Django-blog', help_text='https://github.com/enjoy-binbin/Django-blog', max_length=50, verbose_name='github仓库')),
            ],
            options={
                'verbose_name': '0-站点配置',
                'verbose_name_plural': '0-站点配置',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='越大越前', verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '5-侧边栏',
                'verbose_name_plural': '5-侧边栏',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '4-文章标签',
                'verbose_name_plural': '4-文章标签',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签'),
        ),
    ]
